version: "3.9"

networks:
  app:
    driver: bridge

services:
  nestjs:
    build: ./backend
    ports:
      - 3002:3000
    restart: always
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
    networks:
      - app

  react:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - 3003:8080
    networks:
      - app

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: booking
    volumes:
      - ./mongodb:/data/db
    ports:
      - 27017:27017
    networks:
      - app